const GENERIC_SERVICE = {
  key: 'generic',
  name: 'Generic',
  themeColor: '#6366F1',
  iconExport: 'SiGoogleearth',
  hostRegexes: [],
  pathRegexes: [],
  exampleUrls: [
    'https://www.example.com/video/12345',
    'https://vimeo.com/123456789',
    'https://www.twitch.tv/videos/1234567890',
  ],
  // NEUE FLAGS
  defaultDownloadType: 'video',        // Generic → meistens Video
  disabledDownloadTypes: [],           // alles erlaubt
}

function hostPattern(domain) {
  const escaped = String(domain || '')
    .trim()
    .toLowerCase()
    .replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  return `(?:^|\\.)${escaped}$`
}

const SERVICE_DEFINITIONS_RAW = [
  {
    key: 'youtube',
    name: 'YouTube',
    themeColor: '#FF0000',
    iconExport: 'SiYoutube',
    hostRegexes: [hostPattern('youtube.com'), hostPattern('youtu.be')],
    pathRegexes: [],
    exampleUrls: [
      'https://www.youtube.com/watch?v=PsO6ZnUZI0g',
      'https://youtu.be/PsO6ZnUZI0g',
      'https://www.youtube.com/shorts/PsO6ZnUZI0g',
    ],
    // NEUE FLAGS
    defaultDownloadType: 'audio',        // wie gewünscht
    disabledDownloadTypes: [],
  },
  {
    key: 'netflix',
    name: 'Netflix',
    themeColor: '#E50914',
    iconExport: 'SiNetflix',
    hostRegexes: [hostPattern('netflix.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.netflix.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'tiktok',
    name: 'TikTok',
    themeColor: '#000000',
    accentColor: '#FE2C55',
    iconExport: 'SiTiktok',
    hostRegexes: [hostPattern('tiktok.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.tiktok.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'disney-plus',
    name: 'Disney+',
    themeColor: '#113399',
    iconExport: '',
    hostRegexes: [hostPattern('disneyplus.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.disneyplus.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'amazon-prime-video',
    name: 'Amazon Prime Video',
    themeColor: '#146EB4',
    iconExport: '',
    hostRegexes: [hostPattern('primevideo.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.primevideo.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'twitch',
    name: 'Twitch',
    themeColor: '#9146FF',
    iconExport: 'SiTwitch',
    hostRegexes: [hostPattern('twitch.tv')],
    pathRegexes: [],
    exampleUrls: ['https://www.twitch.tv/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'pornhub',
    name: 'Pornhub',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('pornhub.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.pornhub.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'instagram',
    name: 'Instagram',
    themeColor: '#E4405F',
    iconExport: 'SiInstagram',
    hostRegexes: [hostPattern('instagram.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.instagram.com/'],
    defaultDownloadType: 'video',        // Reels & Videos sind der Haupt-Download
    disabledDownloadTypes: [],
  },
  {
    key: 'facebook',
    name: 'Facebook',
    themeColor: '#1877F2',
    iconExport: 'SiFacebook',
    hostRegexes: [hostPattern('facebook.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.facebook.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'xvideos',
    name: 'XVideos',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('xvideos.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.xvideos.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'max',
    name: 'Max',
    themeColor: '#000000',
    iconExport: 'SiMax',
    hostRegexes: [hostPattern('max.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.max.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'hulu',
    name: 'Hulu',
    themeColor: '#1DB954',
    iconExport: '',
    hostRegexes: [hostPattern('hulu.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.hulu.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'paramount-plus',
    name: 'Paramount+',
    themeColor: '#0066CC',
    iconExport: 'SiParamountplus',
    hostRegexes: [hostPattern('paramountplus.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.paramountplus.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'peacock',
    name: 'Peacock',
    themeColor: '#000000',
    accentColor: '#F5C518',
    iconExport: '',
    hostRegexes: [hostPattern('peacocktv.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.peacocktv.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'apple-tv-plus',
    name: 'Apple TV+',
    themeColor: '#000000',
    iconExport: 'SiAppletv',
    hostRegexes: [hostPattern('tv.apple.com')],
    pathRegexes: [],
    exampleUrls: ['https://tv.apple.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'vimeo',
    name: 'Vimeo',
    themeColor: '#1AB7EA',
    iconExport: 'SiVimeo',
    hostRegexes: [hostPattern('vimeo.com')],
    pathRegexes: [],
    exampleUrls: ['https://vimeo.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'dailymotion',
    name: 'Dailymotion',
    themeColor: '#0066FF',
    iconExport: 'SiDailymotion',
    hostRegexes: [hostPattern('dailymotion.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.dailymotion.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'bilibili',
    name: 'Bilibili',
    themeColor: '#FB7299',
    iconExport: 'SiBilibili',
    hostRegexes: [hostPattern('bilibili.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.bilibili.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'iqiyi',
    name: 'iQIYI',
    themeColor: '#FF6600',
    iconExport: '',
    hostRegexes: [hostPattern('iq.com'), hostPattern('iqiyi.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.iq.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'tencent-video',
    name: 'Tencent Video',
    themeColor: '#FF6600',
    iconExport: 'SiQq',
    hostRegexes: [hostPattern('v.qq.com')],
    pathRegexes: [],
    exampleUrls: ['https://v.qq.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'youku',
    name: 'Youku',
    themeColor: '#FF6600',
    iconExport: '',
    hostRegexes: [hostPattern('youku.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.youku.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'rumble',
    name: 'Rumble',
    themeColor: '#FF6600',
    iconExport: 'SiRumble',
    hostRegexes: [hostPattern('rumble.com')],
    pathRegexes: [],
    exampleUrls: ['https://rumble.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'odysee',
    name: 'Odysee',
    themeColor: '#000000',
    iconExport: 'SiOdysee',
    hostRegexes: [hostPattern('odysee.com')],
    pathRegexes: [],
    exampleUrls: ['https://odysee.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'bitchute',
    name: 'BitChute',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('bitchute.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.bitchute.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'x',
    name: 'X',
    themeColor: '#000000',
    iconExport: 'SiX',
    hostRegexes: [hostPattern('x.com'), hostPattern('twitter.com')],
    pathRegexes: [],
    exampleUrls: [
      'https://x.com/elonmusk/status/1234567890123456789',
      'https://twitter.com/elonmusk/status/1234567890123456789',
    ],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'reddit',
    name: 'Reddit',
    themeColor: '#FF4500',
    iconExport: 'SiReddit',
    hostRegexes: [hostPattern('reddit.com'), hostPattern('redd.it')],
    pathRegexes: [],
    exampleUrls: [
      'https://www.reddit.com/r/aww/comments/abc123/cute_puppy/',
      'https://redd.it/abc123',
    ],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'linkedin',
    name: 'LinkedIn',
    themeColor: '#0A66C2',
    iconExport: '',
    hostRegexes: [hostPattern('linkedin.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.linkedin.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'snapchat',
    name: 'Snapchat',
    themeColor: '#FFFC00',
    iconExport: 'SiSnapchat',
    hostRegexes: [hostPattern('snapchat.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.snapchat.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'pinterest',
    name: 'Pinterest',
    themeColor: '#E60023',
    iconExport: 'SiPinterest',
    hostRegexes: [hostPattern('pinterest.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.pinterest.com/'],
    defaultDownloadType: 'thumbnail',     // hauptsächlich Bilder/Pins
    disabledDownloadTypes: ['video', 'audio'],
  },
  {
    key: 'soundcloud',
    name: 'SoundCloud',
    themeColor: '#FF5500',
    iconExport: 'SiSoundcloud',
    hostRegexes: [hostPattern('soundcloud.com')],
    pathRegexes: [],
    exampleUrls: ['https://soundcloud.com/'],
    defaultDownloadType: 'audio',
    disabledDownloadTypes: ['video'],
  },
  {
    key: 'spotify',
    name: 'Spotify',
    themeColor: '#1DB954',
    iconExport: 'SiSpotify',
    hostRegexes: [hostPattern('spotify.com')],
    pathRegexes: [],
    exampleUrls: ['https://open.spotify.com/'],
    defaultDownloadType: 'audio',
    disabledDownloadTypes: ['video'],
  },
  {
    key: 'jiocinema-hotstar',
    name: 'JioCinema / Hotstar',
    themeColor: '#FF0000',
    iconExport: '',
    hostRegexes: [hostPattern('jiocinema.com'), hostPattern('hotstar.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.jiocinema.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'viu',
    name: 'Viu',
    themeColor: '#FF0000',
    iconExport: '',
    hostRegexes: [hostPattern('viu.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.viu.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'sonyliv',
    name: 'SonyLIV',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('sonyliv.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.sonyliv.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'zee5',
    name: 'Zee5',
    themeColor: '#FF0000',
    iconExport: '',
    hostRegexes: [hostPattern('zee5.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.zee5.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'mxplayer',
    name: 'MX Player',
    themeColor: '#FF0000',
    iconExport: '',
    hostRegexes: [hostPattern('mxplayer.in')],
    pathRegexes: [],
    exampleUrls: ['https://www.mxplayer.in/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'tubi',
    name: 'Tubi',
    themeColor: '#7400B8',
    iconExport: 'SiTubi',
    hostRegexes: [hostPattern('tubitv.com')],
    pathRegexes: [],
    exampleUrls: ['https://tubitv.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'pluto-tv',
    name: 'Pluto TV',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('pluto.tv')],
    pathRegexes: [],
    exampleUrls: ['https://pluto.tv/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'roku-channel',
    name: 'The Roku Channel',
    themeColor: '#000000',
    iconExport: 'SiRoku',
    hostRegexes: [hostPattern('therokuchannel.com')],
    pathRegexes: [],
    exampleUrls: ['https://therokuchannel.roku.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'crackle',
    name: 'Crackle',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('crackle.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.crackle.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'discovery-plus',
    name: 'Discovery+',
    themeColor: '#FF6600',
    iconExport: '',
    hostRegexes: [hostPattern('discoveryplus.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.discoveryplus.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'espn-plus',
    name: 'ESPN+',
    themeColor: '#CC0000',
    iconExport: '',
    hostRegexes: [hostPattern('espn.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.espn.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'nba-league-pass',
    name: 'NBA League Pass',
    themeColor: '#000000',
    iconExport: 'SiNba',
    hostRegexes: [hostPattern('nba.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.nba.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'nfl-plus',
    name: 'NFL+',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('nfl.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.nfl.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'mlb-tv',
    name: 'MLB.TV',
    themeColor: '#000000',
    iconExport: 'SiMlb',
    hostRegexes: [hostPattern('mlb.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.mlb.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'formula1-tv',
    name: 'Formula 1 TV',
    themeColor: '#E10600',
    iconExport: '',
    hostRegexes: [hostPattern('formula1.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.formula1.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'dazn',
    name: 'DAZN',
    themeColor: '#FF0000',
    iconExport: 'SiDazn',
    hostRegexes: [hostPattern('dazn.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.dazn.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'sky',
    name: 'Sky',
    themeColor: '#000000',
    iconExport: 'SiSky',
    hostRegexes: [hostPattern('sky.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.sky.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'itv',
    name: 'ITV',
    themeColor: '#FF0000',
    iconExport: 'SiItvx',
    hostRegexes: [hostPattern('itv.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.itv.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'bbc-iplayer',
    name: 'BBC iPlayer',
    themeColor: '#BB1919',
    iconExport: '',
    hostRegexes: [hostPattern('bbc.co.uk')],
    pathRegexes: ['^/iplayer(?:/|$)'],
    exampleUrls: ['https://www.bbc.co.uk/iplayer'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'ard-zdf',
    name: 'ARD Mediathek / ZDF',
    themeColor: '#000000',
    iconExport: 'SiZdf',
    hostRegexes: [hostPattern('ardmediathek.de'), hostPattern('zdf.de')],
    pathRegexes: [],
    exampleUrls: ['https://www.ardmediathek.de/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'france-tv',
    name: 'France.tv',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('france.tv')],
    pathRegexes: [],
    exampleUrls: ['https://www.france.tv/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'raiplay',
    name: 'RaiPlay',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('raiplay.it')],
    pathRegexes: [],
    exampleUrls: ['https://www.raiplay.it/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'rtve',
    name: 'RTVE',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('rtve.es')],
    pathRegexes: [],
    exampleUrls: ['https://www.rtve.es/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'nrk',
    name: 'NRK',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('nrk.no')],
    pathRegexes: [],
    exampleUrls: ['https://www.nrk.no/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'svt-play',
    name: 'SVT Play',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('svtplay.se')],
    pathRegexes: [],
    exampleUrls: ['https://www.svtplay.se/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'dr-tv',
    name: 'DR TV',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('dr.dk')],
    pathRegexes: [],
    exampleUrls: ['https://www.dr.dk/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'yle-areena',
    name: 'Yle Areena',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('areena.yle.fi')],
    pathRegexes: [],
    exampleUrls: ['https://areena.yle.fi/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'cbc-gem',
    name: 'CBC Gem',
    themeColor: '#000000',
    iconExport: 'SiCbc',
    hostRegexes: [hostPattern('gem.cbc.ca')],
    pathRegexes: [],
    exampleUrls: ['https://gem.cbc.ca/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'abc-iview',
    name: 'ABC iview',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('iview.abc.net.au')],
    pathRegexes: [],
    exampleUrls: ['https://iview.abc.net.au/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: '9now',
    name: '9Now',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('9now.com.au')],
    pathRegexes: [],
    exampleUrls: ['https://www.9now.com.au/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: '7plus',
    name: '7plus',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('7plus.com.au')],
    pathRegexes: [],
    exampleUrls: ['https://7plus.com.au/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: '10play',
    name: '10 play',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('10play.com.au')],
    pathRegexes: [],
    exampleUrls: ['https://10play.com.au/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'globo',
    name: 'Globo',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('globoplay.globo.com')],
    pathRegexes: [],
    exampleUrls: ['https://globoplay.globo.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'caracol-play',
    name: 'Caracol Play',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('caracoltv.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.caracoltv.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'telemundo',
    name: 'Telemundo',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('telemundo.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.telemundo.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'univision',
    name: 'Univision',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('univision.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.univision.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'teletrece',
    name: 'Teletrece',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('13.cl')],
    pathRegexes: [],
    exampleUrls: ['https://www.13.cl/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'afreecatv-soop',
    name: 'AfreecaTV / SOOP',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('afreecatv.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.afreecatv.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'chzzk',
    name: 'Chzzk',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('chzzk.naver.com')],
    pathRegexes: [],
    exampleUrls: ['https://chzzk.naver.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'naver-tv',
    name: 'Naver TV',
    themeColor: '#03C75A',
    iconExport: 'SiNaver',
    hostRegexes: [hostPattern('tv.naver.com')],
    pathRegexes: [],
    exampleUrls: ['https://tv.naver.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'kakao-tv',
    name: 'Kakao TV',
    themeColor: '#FFCD00',
    iconExport: 'SiKakao',
    hostRegexes: [hostPattern('tv.kakao.com')],
    pathRegexes: [],
    exampleUrls: ['https://tv.kakao.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'douyu',
    name: 'Douyu',
    themeColor: '#FF6600',
    iconExport: '',
    hostRegexes: [hostPattern('douyu.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.douyu.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'huya',
    name: 'Huya',
    themeColor: '#FF6600',
    iconExport: '',
    hostRegexes: [hostPattern('huya.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.huya.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: '17live',
    name: '17 Live',
    themeColor: '#FF0000',
    iconExport: '',
    hostRegexes: [hostPattern('17.live')],
    pathRegexes: [],
    exampleUrls: ['https://17.live/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'bigo-live',
    name: 'Bigo Live',
    themeColor: '#FF0000',
    iconExport: '',
    hostRegexes: [hostPattern('bigo.tv')],
    pathRegexes: [],
    exampleUrls: ['https://www.bigo.tv/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'liveme',
    name: 'LiveMe',
    themeColor: '#FF0000',
    iconExport: '',
    hostRegexes: [hostPattern('liveme.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.liveme.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'nonolive',
    name: 'Nonolive',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('nonolive.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.nonolive.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'onlyfans',
    name: 'OnlyFans',
    themeColor: '#000000',
    iconExport: 'SiOnlyfans',
    hostRegexes: [hostPattern('onlyfans.com')],
    pathRegexes: [],
    exampleUrls: ['https://onlyfans.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'fansly',
    name: 'Fansly',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('fansly.com')],
    pathRegexes: [],
    exampleUrls: ['https://fansly.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'manyvids',
    name: 'ManyVids',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('manyvids.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.manyvids.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'stripchat',
    name: 'Stripchat',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('stripchat.com')],
    pathRegexes: [],
    exampleUrls: ['https://stripchat.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'chaturbate',
    name: 'Chaturbate',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('chaturbate.com')],
    pathRegexes: [],
    exampleUrls: ['https://chaturbate.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'beeg',
    name: 'Beeg',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('beeg.com')],
    pathRegexes: [],
    exampleUrls: ['https://beeg.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'xhamster',
    name: 'XHamster',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('xhamster.com')],
    pathRegexes: [],
    exampleUrls: ['https://xhamster.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'xnxx',
    name: 'XNXX',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('xnxx.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.xnxx.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'youporn',
    name: 'YouPorn',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('youporn.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.youporn.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'redtube',
    name: 'RedTube',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('redtube.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.redtube.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'spankbang',
    name: 'SpankBang',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('spankbang.com')],
    pathRegexes: [],
    exampleUrls: ['https://spankbang.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'eporner',
    name: 'Eporner',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('eporner.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.eporner.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'motherless',
    name: 'Motherless',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('motherless.com')],
    pathRegexes: [],
    exampleUrls: ['https://motherless.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'thisvid',
    name: 'ThisVid',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('thisvid.com')],
    pathRegexes: [],
    exampleUrls: ['https://thisvid.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'newgrounds',
    name: 'Newgrounds',
    themeColor: '#000000',
    iconExport: 'SiNewgrounds',
    hostRegexes: [hostPattern('newgrounds.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.newgrounds.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'gamejolt',
    name: 'GameJolt',
    themeColor: '#000000',
    iconExport: 'SiGamejolt',
    hostRegexes: [hostPattern('gamejolt.com')],
    pathRegexes: [],
    exampleUrls: ['https://gamejolt.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'itch-io',
    name: 'itch.io',
    themeColor: '#FA5C5C',
    iconExport: 'SiItchdotio',
    hostRegexes: [hostPattern('itch.io')],
    pathRegexes: [],
    exampleUrls: ['https://itch.io/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'steam',
    name: 'Steam',
    themeColor: '#000000',
    iconExport: 'SiSteam',
    hostRegexes: [hostPattern('store.steampowered.com')],
    pathRegexes: [],
    exampleUrls: ['https://store.steampowered.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'kick',
    name: 'Kick',
    themeColor: '#53FC19',
    iconExport: 'SiKick',
    hostRegexes: [hostPattern('kick.com')],
    pathRegexes: [],
    exampleUrls: ['https://kick.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'trovo',
    name: 'Trovo',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('trovo.live')],
    pathRegexes: [],
    exampleUrls: ['https://trovo.live/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'dlive',
    name: 'DLive',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('dlive.tv')],
    pathRegexes: [],
    exampleUrls: ['https://dlive.tv/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'sling-tv',
    name: 'Sling TV',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('sling.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.sling.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'fubotv',
    name: 'FuboTV',
    themeColor: '#000000',
    iconExport: 'SiFubo',
    hostRegexes: [hostPattern('fubo.tv')],
    pathRegexes: [],
    exampleUrls: ['https://www.fubo.tv/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'directv-stream',
    name: 'DirecTV Stream',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('directv.com')],
    pathRegexes: ['^/stream(?:/|$)'],
    exampleUrls: ['https://www.directv.com/stream/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'acfun',
    name: 'AcFun',
    themeColor: '#FF4D4F',
    iconExport: '',
    hostRegexes: [hostPattern('acfun.cn')],
    pathRegexes: [],
    exampleUrls: ['https://www.acfun.cn/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'aparat',
    name: 'Aparat',
    themeColor: '#000000',
    iconExport: 'SiAparat',
    hostRegexes: [hostPattern('aparat.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.aparat.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'rutube',
    name: 'Rutube',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('rutube.ru')],
    pathRegexes: [],
    exampleUrls: ['https://rutube.ru/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'freevee',
    name: 'IMDb TV / Freevee',
    themeColor: '#146EB4',
    iconExport: '',
    hostRegexes: [hostPattern('amazon.com')],
    pathRegexes: ['^/freevee(?:/|$)'],
    exampleUrls: ['https://www.amazon.com/freevee'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'crunchyroll',
    name: 'Crunchyroll',
    themeColor: '#FF6600',
    iconExport: 'SiCrunchyroll',
    hostRegexes: [hostPattern('crunchyroll.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.crunchyroll.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'funimation',
    name: 'Funimation',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('funimation.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.funimation.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'hidive',
    name: 'HIDIVE',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('hidive.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.hidive.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'wakanim',
    name: 'Wakanim',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('wakanim.tv')],
    pathRegexes: [],
    exampleUrls: ['https://www.wakanim.tv/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'vrv',
    name: 'VRV',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('vrv.co')],
    pathRegexes: [],
    exampleUrls: ['https://vrv.co/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'imdb',
    name: 'IMDb',
    themeColor: '#F5C518',
    iconExport: 'SiImdb',
    hostRegexes: [hostPattern('imdb.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.imdb.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'rotten-tomatoes',
    name: 'Rotten Tomatoes',
    themeColor: '#FA320A',
    iconExport: 'SiRottentomatoes',
    hostRegexes: [hostPattern('rottentomatoes.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.rottentomatoes.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'metacritic',
    name: 'Metacritic',
    themeColor: '#000000',
    iconExport: 'SiMetacritic',
    hostRegexes: [hostPattern('metacritic.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.metacritic.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'ign',
    name: 'IGN',
    themeColor: '#000000',
    iconExport: 'SiIgn',
    hostRegexes: [hostPattern('ign.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.ign.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'gamespot',
    name: 'GameSpot',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('gamespot.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.gamespot.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'giant-bomb',
    name: 'Giant Bomb',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('giantbomb.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.giantbomb.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'vevo',
    name: 'Vevo',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('vevo.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.vevo.com/'],
    defaultDownloadType: 'video',         // Musikvideos → Video
    disabledDownloadTypes: [],
  },
  {
    key: 'bandcamp',
    name: 'Bandcamp',
    themeColor: '#1DA1F2',
    iconExport: 'SiBandcamp',
    hostRegexes: [hostPattern('bandcamp.com')],
    pathRegexes: [],
    exampleUrls: ['https://bandcamp.com/'],
    defaultDownloadType: 'audio',
    disabledDownloadTypes: ['video'],
  },
  {
    key: 'mixcloud',
    name: 'Mixcloud',
    themeColor: '#FF5500',
    iconExport: 'SiMixcloud',
    hostRegexes: [hostPattern('mixcloud.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.mixcloud.com/'],
    defaultDownloadType: 'audio',
    disabledDownloadTypes: ['video'],
  },
  {
    key: 'audius',
    name: 'Audius',
    themeColor: '#C600FF',
    iconExport: '',
    hostRegexes: [hostPattern('audius.co')],
    pathRegexes: [],
    exampleUrls: ['https://audius.co/'],
    defaultDownloadType: 'audio',
    disabledDownloadTypes: ['video'],
  },
  {
    key: 'audiomack',
    name: 'Audiomack',
    themeColor: '#000000',
    iconExport: 'SiAudiomack',
    hostRegexes: [hostPattern('audiomack.com')],
    pathRegexes: [],
    exampleUrls: ['https://audiomack.com/'],
    defaultDownloadType: 'audio',
    disabledDownloadTypes: ['video'],
  },
  {
    key: 'last-fm',
    name: 'Last.fm',
    themeColor: '#D51007',
    iconExport: 'SiLastdotfm',
    hostRegexes: [hostPattern('last.fm')],
    pathRegexes: [],
    exampleUrls: ['https://www.last.fm/'],
    defaultDownloadType: 'audio',
    disabledDownloadTypes: ['video'],
  },
  {
    key: 'reverbnation',
    name: 'ReverbNation',
    themeColor: '#000000',
    iconExport: 'SiReverbnation',
    hostRegexes: [hostPattern('reverbnation.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.reverbnation.com/'],
    defaultDownloadType: 'audio',
    disabledDownloadTypes: ['video'],
  },
  {
    key: 'jamendo',
    name: 'Jamendo',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('jamendo.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.jamendo.com/'],
    defaultDownloadType: 'audio',
    disabledDownloadTypes: ['video'],
  },
  {
    key: 'epidemic-sound',
    name: 'Epidemic Sound',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('epidemicsound.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.epidemicsound.com/'],
    defaultDownloadType: 'audio',
    disabledDownloadTypes: ['video'],
  },
  {
    key: 'artlist',
    name: 'Artlist',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('artlist.io')],
    pathRegexes: [],
    exampleUrls: ['https://artlist.io/'],
    defaultDownloadType: 'audio',
    disabledDownloadTypes: ['video'],
  },
  {
    key: 'storyblocks',
    name: 'Storyblocks',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('storyblocks.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.storyblocks.com/'],
    defaultDownloadType: 'video',         // Stock-Video
    disabledDownloadTypes: [],
  },
  {
    key: 'shutterstock-video',
    name: 'Shutterstock',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('shutterstock.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.shutterstock.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'getty-images-video',
    name: 'Getty Images',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('gettyimages.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.gettyimages.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'pond5',
    name: 'Pond5',
    themeColor: '#000000',
    iconExport: 'SiPond5',
    hostRegexes: [hostPattern('pond5.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.pond5.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'motion-array',
    name: 'Motion Array',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('motionarray.com')],
    pathRegexes: [],
    exampleUrls: ['https://motionarray.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'envato-elements',
    name: 'Envato Elements',
    themeColor: '#000000',
    iconExport: 'SiEnvato',
    hostRegexes: [hostPattern('elements.envato.com')],
    pathRegexes: [],
    exampleUrls: ['https://elements.envato.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'brightcove',
    name: 'Brightcove',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('brightcove.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.brightcove.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'kaltura',
    name: 'Kaltura',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('kaltura.com')],
    pathRegexes: [],
    exampleUrls: ['https://corp.kaltura.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'jw-player',
    name: 'JW Player',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('jwplayer.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.jwplayer.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'wistia',
    name: 'Wistia',
    themeColor: '#00A3FF',
    iconExport: 'SiWistia',
    hostRegexes: [hostPattern('wistia.com')],
    pathRegexes: [],
    exampleUrls: ['https://wistia.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'vidyard',
    name: 'Vidyard',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('vidyard.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.vidyard.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'panopto',
    name: 'Panopto',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('panopto.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.panopto.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'mediasite',
    name: 'Mediasite',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('mediasite.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.mediasite.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'vimeo-livestream',
    name: 'Vimeo Livestream',
    themeColor: '#1AB7EA',
    iconExport: 'SiVimeo',
    hostRegexes: [hostPattern('vimeo.com')],
    pathRegexes: ['^/live(?:/|$)'],
    exampleUrls: ['https://vimeo.com/live'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'restream',
    name: 'Restream',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('restream.io')],
    pathRegexes: [],
    exampleUrls: ['https://restream.io/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'streamyard',
    name: 'StreamYard',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('streamyard.com')],
    pathRegexes: [],
    exampleUrls: ['https://streamyard.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'castr',
    name: 'Castr',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('castr.com')],
    pathRegexes: [],
    exampleUrls: ['https://castr.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'dacast',
    name: 'Dacast',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('dacast.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.dacast.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'wowza',
    name: 'Wowza',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('wowza.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.wowza.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'ant-media',
    name: 'Ant Media',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('antmedia.io')],
    pathRegexes: [],
    exampleUrls: ['https://antmedia.io/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'mux',
    name: 'Mux',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('mux.com')],
    pathRegexes: [],
    exampleUrls: ['https://mux.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'cloudflare-stream',
    name: 'Cloudflare Stream',
    themeColor: '#F6821F',
    iconExport: 'SiCloudflare',
    hostRegexes: [hostPattern('cloudflare.com')],
    pathRegexes: ['^/products/cloudflare-stream(?:/|$)'],
    exampleUrls: ['https://www.cloudflare.com/products/cloudflare-stream/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'aws-elemental',
    name: 'AWS Elemental',
    themeColor: '#FF9900',
    iconExport: '',
    hostRegexes: [hostPattern('aws.amazon.com')],
    pathRegexes: ['^/elemental(?:/|$)'],
    exampleUrls: ['https://aws.amazon.com/elemental/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'azure-media-services',
    name: 'Azure Media Services',
    themeColor: '#0078D4',
    iconExport: '',
    hostRegexes: [hostPattern('azure.microsoft.com')],
    pathRegexes: [],
    exampleUrls: ['https://azure.microsoft.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'ibm-video-streaming',
    name: 'IBM Video Streaming',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('ibm.com')],
    pathRegexes: ['^/products/video-streaming(?:/|$)'],
    exampleUrls: ['https://www.ibm.com/products/video-streaming'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'uscreen',
    name: 'Uscreen',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('uscreen.tv')],
    pathRegexes: [],
    exampleUrls: ['https://www.uscreen.tv/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'vhx',
    name: 'VHX',
    themeColor: '#1AB7EA',
    iconExport: 'SiVimeo',
    hostRegexes: [hostPattern('vhx.tv')],
    pathRegexes: [],
    exampleUrls: ['https://www.vhx.tv/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'patreon-video',
    name: 'Patreon',
    themeColor: '#FF424D',
    iconExport: 'SiPatreon',
    hostRegexes: [hostPattern('patreon.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.patreon.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'substack-video',
    name: 'Substack',
    themeColor: '#FF6719',
    iconExport: 'SiSubstack',
    hostRegexes: [hostPattern('substack.com')],
    pathRegexes: [],
    exampleUrls: ['https://substack.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'kickstarter-video',
    name: 'Kickstarter',
    themeColor: '#05CE78',
    iconExport: 'SiKickstarter',
    hostRegexes: [hostPattern('kickstarter.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.kickstarter.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'indiegogo-video',
    name: 'Indiegogo',
    themeColor: '#E5102A',
    iconExport: '',
    hostRegexes: [hostPattern('indiegogo.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.indiegogo.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'gofundme-video',
    name: 'GoFundMe',
    themeColor: '#00B2A9',
    iconExport: 'SiGofundme',
    hostRegexes: [hostPattern('gofundme.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.gofundme.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'masterclass',
    name: 'MasterClass',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('masterclass.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.masterclass.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'skillshare',
    name: 'Skillshare',
    themeColor: '#FF5A00',
    iconExport: 'SiSkillshare',
    hostRegexes: [hostPattern('skillshare.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.skillshare.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'udemy',
    name: 'Udemy',
    themeColor: '#A435F0',
    iconExport: 'SiUdemy',
    hostRegexes: [hostPattern('udemy.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.udemy.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'coursera-video',
    name: 'Coursera',
    themeColor: '#0056D2',
    iconExport: 'SiCoursera',
    hostRegexes: [hostPattern('coursera.org')],
    pathRegexes: [],
    exampleUrls: ['https://www.coursera.org/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'edx',
    name: 'edX',
    themeColor: '#000000',
    iconExport: 'SiEdx',
    hostRegexes: [hostPattern('edx.org')],
    pathRegexes: [],
    exampleUrls: ['https://www.edx.org/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'khan-academy',
    name: 'Khan Academy',
    themeColor: '#14BF96',
    iconExport: 'SiKhanacademy',
    hostRegexes: [hostPattern('khanacademy.org')],
    pathRegexes: [],
    exampleUrls: ['https://www.khanacademy.org/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'brilliant',
    name: 'Brilliant',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('brilliant.org')],
    pathRegexes: [],
    exampleUrls: ['https://brilliant.org/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'pluralsight',
    name: 'Pluralsight',
    themeColor: '#F15B2A',
    iconExport: 'SiPluralsight',
    hostRegexes: [hostPattern('pluralsight.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.pluralsight.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'linkedin-learning',
    name: 'LinkedIn Learning',
    themeColor: '#0A66C2',
    iconExport: '',
    hostRegexes: [hostPattern('linkedin.com')],
    pathRegexes: ['^/learning(?:/|$)'],
    exampleUrls: ['https://www.linkedin.com/learning/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'frontend-masters',
    name: 'Frontend Masters',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('frontendmasters.com')],
    pathRegexes: [],
    exampleUrls: ['https://frontendmasters.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'egghead',
    name: 'Egghead.io',
    themeColor: '#000000',
    iconExport: 'SiEgghead',
    hostRegexes: [hostPattern('egghead.io')],
    pathRegexes: [],
    exampleUrls: ['https://egghead.io/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'laracasts',
    name: 'Laracasts',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('laracasts.com')],
    pathRegexes: [],
    exampleUrls: ['https://laracasts.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'treehouse',
    name: 'Treehouse',
    themeColor: '#000000',
    iconExport: 'SiTreehouse',
    hostRegexes: [hostPattern('teamtreehouse.com')],
    pathRegexes: [],
    exampleUrls: ['https://teamtreehouse.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'packt',
    name: 'Packt',
    themeColor: '#000000',
    iconExport: 'SiPackt',
    hostRegexes: [hostPattern('packtpub.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.packtpub.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'oreilly',
    name: 'O\'Reilly',
    themeColor: '#000000',
    iconExport: 'SiOreilly',
    hostRegexes: [hostPattern('oreilly.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.oreilly.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'lynda',
    name: 'Lynda.com',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('lynda.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.lynda.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'curiositystream',
    name: 'CuriosityStream',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('curiositystream.com')],
    pathRegexes: [],
    exampleUrls: ['https://curiositystream.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'magellan-tv',
    name: 'MagellanTV',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('magellantv.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.magellantv.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'gaia',
    name: 'Gaia',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('gaia.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.gaia.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'the-great-courses',
    name: 'The Great Courses',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('thegreatcourses.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.thegreatcourses.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'wondrium',
    name: 'Wondrium',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('wondrium.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.wondrium.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'documentary-heaven',
    name: 'Documentary Heaven',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('documentaryheaven.com')],
    pathRegexes: [],
    exampleUrls: ['https://documentaryheaven.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'filmzie',
    name: 'Filmzie',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('filmzie.com')],
    pathRegexes: [],
    exampleUrls: ['https://filmzie.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'kanopy',
    name: 'Kanopy',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('kanopy.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.kanopy.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'hoopla',
    name: 'Hoopla',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('hoopladigital.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.hoopladigital.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'overdrive-libby',
    name: 'OverDrive / Libby',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('overdrive.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.overdrive.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'pbs',
    name: 'PBS',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('pbs.org')],
    pathRegexes: [],
    exampleUrls: ['https://www.pbs.org/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'nfb',
    name: 'NFB',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('nfb.ca')],
    pathRegexes: [],
    exampleUrls: ['https://www.nfb.ca/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
  {
    key: 'nz-on-screen',
    name: 'NZ On Screen',
    themeColor: '#000000',
    iconExport: '',
    hostRegexes: [hostPattern('nzonscreen.com')],
    pathRegexes: [],
    exampleUrls: ['https://www.nzonscreen.com/'],
    defaultDownloadType: 'video',
    disabledDownloadTypes: [],
  },
]

function freezeService(service) {
  return Object.freeze({
    ...service,
    accentColor: service.accentColor || '',
    iconExport: service.iconExport || '',
    hostRegexes: Object.freeze([...(service.hostRegexes || [])]),
    pathRegexes: Object.freeze([...(service.pathRegexes || [])]),
    exampleUrls: Object.freeze([...(service.exampleUrls || [])]),
    // neue Flags werden automatisch mitkopiert
    defaultDownloadType: service.defaultDownloadType || 'video',
    disabledDownloadTypes: Object.freeze([...(service.disabledDownloadTypes || [])]),
  })
}

export const GENERIC_SERVICE_KEY = GENERIC_SERVICE.key
export const SERVICE_DEFINITIONS = Object.freeze([
  ...SERVICE_DEFINITIONS_RAW.map(freezeService),
  freezeService(GENERIC_SERVICE),
])